### ISSUE TITLE
When publishing an image to an unsupported AWS region, error message is not correctly displayed

### ISSUE THREAD

**Issue by cinlloc** [usharesoft/hammr#293]
Step to reproduce:
1. Having a hammr connected to a forge with an AWS cred account `My Amazon Account`
2. Create an appliance (e.g. CentOS 7)
3. Generate to AWS
4. Edit a file `publish-aws-cn.yml`:

```
---
builders:
- type: Amazon AWS
  account:
    name: My Amazon Account
  region: cn-north-1
  bucket: testsohammr 
```

5. Edit a file `publish-aws-toto.yml`:
```
---
builders:
- type: Amazon AWS
  account:
    name: My Amazon Account
  region: toto
  bucket: testsohammr 
```

6. Publish generated image with Hammr to cn-north-1: 
`hammr image publish --id x --file publish-aws-cn.yml`

Expected: 

```
ERROR: Publication to 'My Amazon Account' error: This region is not managed. Please choose another one.
```

Actual: 

```
ERROR: Publication to 'My Amazon Account' error: This region is not managed. Please choose another one.
This region is not managed. Please choose another one.
This region is not managed. Please choose another one.
```

7. Publish generated image with Hammr to invalid `toto` region: 
`hammr image publish --id x --file publish-aws-toto.yml`

Expected: 

```
ERROR: Publication to 'My Amazon Account' error: This region is not valid. Please choose another one.
```

Actual: 
```
ERROR: Publication to 'My Amazon Account' error: Internal server error.
Please contact support
```
