### ISSUE TITLE
builder for Google Compute Engine fails

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#408]
When trying to build a template with the builder below, the following error is displayed:
```
hammr> template build --file template2.yml
INFO: You provided a yaml file, checking...
Generating 'Google Compute Engine' image (1/1)
ERROR: Builder type unknown: Google Compute Engine
```
I managed to fix the issue by:
- replacing def generate_gce with def generate_google in file hammr/utils/generate_utils.py
- replacing "Google Compute Engine" with "google" in the first type occurrence in the template yaml file.

```
builders:
- type: "Google Compute Engine" 
  account:
    type: "Google Compute Engine"
    name: My GCE Account
    username: my@email.com
    certPassword: XXXXXXX
    cert: "/my/certificate/gce.p12"
  computeZone: europe-west1-a
  bucketLocation: EU
  bucket: mybucket
  projectId: my-project
  storageClass: STANDARD
  diskNamePrefix: uss-
  description: CentOS Core machine image
```
