### ISSUE TITLE
File with same name in same directory in template archive

### ISSUE THREAD

**Issue by ludop-usharesoft** [usharesoft/hammr#488]
When using nextcloud to host files referenced by a template, you may have a UForge template containing something like the following:
```
  bundles:
  - name: "MariaDB"
    version: "10.1.16"
    maintainer: "UShareSoft"
    files:
    - name: "MariaDB-client-10.1.16-1.el7.centos.x86_64.rpm"
      ownerGroup: "root:root"
      rights: "755"
      tag: "softwarefile"
      source: "https://nextcloud.usharesoft.com/index.php/s/ETmPcgkyjyyTiFB/download"
      install: true
      md5sum: "e8c5984264e45074d814137f10aa7842"
      sha256sum: "1faf8422c72179df62c2f3aeebe9351910ea976b4da2bdb11622d92f4916c14a"
    - name: "MariaDB-common-10.1.16-1.el7.centos.x86_64.rpm"
      ownerGroup: "root:root"
      rights: "755"
      tag: "softwarefile"
      source: "https://nextcloud.usharesoft.com/index.php/s/e9bqXKgx37XRcqT/download"
      install: true
      md5sum: "6876b057c551ab4e725fa1130f9fc042"
      sha256sum: "52cb56aa17c33851ca0ea2a7e8746ea00fa68f0d1faaea08ca3e37b32ab2a38f"
```
Both the source URL are ending with "download" but references different files.
The problem is that hammr use this "download" string as the name put in the template archive.
So as the files are in the same bundle, hammr generated a tar.gz archive with two "download" file in the same directory.
So when UForge extract this archive in order to import the template, the files are overwritten by one another.
And the template yaml inside the archive contains the same "source: bundles/MariaDB/10.1.16/download" for different files.
